# config.yml
data_dir: "./Dataset"
collection_name: "database"
chunk_size: 400
chunk_overlap: 40
embedding_model: "nomic-embed-text"
batch_size: 32
milvus_path: "./milvus_data_U.db"
ollama_host: "127.0.0.1"
ollama_port: "11434"
chat_model: "llama3.2:latest"
top_k: 3
score_threshold: 0.5
system_prompt: "You are a assistant. Please reply based on the provided context. Be polite."